# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import filetransfer.filetransfer_pb2 as filetransfer__pb2


class FileTransferServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ServerSideStreamFun = channel.unary_stream(
        '/filetransfer.FileTransferService/ServerSideStreamFun',
        request_serializer=filetransfer__pb2.RequestData.SerializeToString,
        response_deserializer=filetransfer__pb2.ResponseData.FromString,
        )


class FileTransferServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ServerSideStreamFun(self, request, context):
    """����������ʽrpc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ServerSideStreamFun': grpc.unary_stream_rpc_method_handler(
          servicer.ServerSideStreamFun,
          request_deserializer=filetransfer__pb2.RequestData.FromString,
          response_serializer=filetransfer__pb2.ResponseData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'filetransfer.FileTransferService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
